### ISSUE TITLE
Issue with docker_build.py

### ISSUE THREAD

**Issue by mvish7** [RobotLocomotion/pytorch-dense-correspondence#198] opened 2019-06-24 15:06 UTC
Hello,
I'm trying to set up the docker image on ubuntu 16.04 by following the Getting Started [Tutorial](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/tutorial_getting_started.md). When I run the ./docker_build.py i get following error which I can't decipher. Can you please help me into this?

terminal extract:

` mhv7rng@RNGX4031:~$ cd pytorch-dense-correspondence mhv7rng@RNGX4031:~/pytorch-dense-correspondence$ cd docker
mhv7rng@RNGX4031:~/pytorch-dense-correspondence/docker$ ./docker_build.py
building docker container . . . 
building docker image named  mhv7rng-pytorch-dense-correspondence
command = 
 
 docker build --build-arg USER_NAME=mhv7rng 			--build-arg USER_PASSWORD=password 			--build-arg USER_ID=1584004904 		--build-arg USER_GID=1584004904 -t mhv7rng-pytorch-dense-correspondence -f pytorch-dense-correspondence.dockerfile .

executing shell command
Sending build context to Docker daemon  17.92kB
Step 1/28 : FROM nvidia/cuda:8.0-devel-ubuntu16.04
 ---> dab5c9f3cbed
Step 2/28 : ARG USER_NAME
 ---> Using cache
 ---> ad58747699b3
Step 3/28 : ARG USER_PASSWORD
 ---> Using cache
 ---> 53aab4793e52
Step 4/28 : ARG USER_ID
 ---> Using cache
 ---> d064dce876f6
Step 5/28 : ARG USER_GID
 ---> Using cache
 ---> 5bf2c030173b
Step 6/28 : RUN apt-get update
 ---> Using cache
 ---> 0f5831f1ab83
Step 7/28 : RUN apt install sudo
 ---> Running in 1d83d24d096b

**WARNING: apt does not have a stable CLI interface. Use with caution in scripts.**

Reading package lists...
Building dependency tree...
Reading state information...
**E: Unable to locate package sudo**
**The command '/bin/sh -c apt install sudo' returned a non-zero code: 100**

`

**Comment by manuelli** [comment] 2019-06-26 22:43
Hi,

I just tried a clean build of the docker image and wasn't able to reproduce your issue on my machine. It looks like the `apt install sudo` command is failing inside the docker image for some reason. A PR #199 was just merged so you might try with a clean build from that point.

**Closed by manuelli** 2019-06-26 22:43 UTC
